export const ENDGAME_PUZZLES = [
  {
    id: 'end-001',
    title: '킹+폰 엔드게임 #1',
    description: '폰을 프로모션시키세요.',
    difficulty: 2,
    fen: '8/8/8/8/8/4K3/4P3/4k3 w - - 0 1',
    turn: 'w',
    solution: ['Kd3'],
    hints: ['킹을 전진시켜 폰을 호위하세요.'],
  },
  {
    id: 'end-002',
    title: '룩 엔드게임 #1',
    description: '룩으로 승리하세요.',
    difficulty: 3,
    fen: '8/8/8/8/8/4K3/R7/4k3 w - - 0 1',
    turn: 'w',
    solution: ['Kd3'],
    hints: ['킹을 접근시켜 룩과 협력하세요.'],
  },
  {
    id: 'end-003',
    title: '퀸 vs 킹',
    description: '퀸으로 체크메이트하세요.',
    difficulty: 2,
    fen: '8/8/8/8/3k4/8/1K6/Q7 w - - 0 1',
    turn: 'w',
    solution: ['Qa4+'],
    hints: ['킹을 가장자리로 몰아세요.'],
  },
  {
    id: 'end-004',
    title: '통과폰 레이스',
    description: '폰 레이스에서 승리하세요.',
    difficulty: 3,
    fen: '8/p7/8/8/8/8/7P/8 w - - 0 1',
    turn: 'w',
    solution: ['h4'],
    hints: ['폰을 빠르게 전진시키세요.'],
  },
  {
    id: 'end-005',
    title: '비숍 엔드게임',
    description: '비숍과 킹으로 승리 포지션을 만드세요.',
    difficulty: 4,
    fen: '8/8/2k5/8/8/2K5/1B6/8 w - - 0 1',
    turn: 'w',
    solution: ['Kd4'],
    hints: ['킹을 중앙으로 전진시키세요.'],
  },
];
