export const MATE_IN_1_PUZZLES = [
  {
    id: 'mi1-001',
    title: '1수 체크메이트 #1',
    description: '백이 한 수로 체크메이트할 수 있습니다.',
    difficulty: 1,
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
    turn: 'w',
    solution: ['Qxf7#'],
    hints: ['f7 칸을 공격할 수 있는 기물을 찾으세요.'],
  },
  {
    id: 'mi1-002',
    title: '1수 체크메이트 #2',
    description: '백이 한 수로 체크메이트할 수 있습니다.',
    difficulty: 1,
    fen: 'rnbqkbnr/pppp1ppp/8/4p3/6P1/5P2/PPPPP2P/RNBQKBNR b KQkq - 0 2',
    turn: 'b',
    solution: ['Qh4#'],
    hints: ['퀸으로 대각선 체크를 노리세요.'],
  },
  {
    id: 'mi1-003',
    title: '1수 체크메이트 #3',
    description: '백이 한 수로 체크메이트할 수 있습니다.',
    difficulty: 1,
    fen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    turn: 'w',
    solution: ['Re8#'],
    hints: ['룩으로 8랭크를 공격하세요.'],
  },
  {
    id: 'mi1-004',
    title: '1수 체크메이트 #4',
    description: '백이 한 수로 체크메이트할 수 있습니다.',
    difficulty: 1,
    fen: '5rk1/5ppp/8/8/8/8/2Q2PPP/6K1 w - - 0 1',
    turn: 'w',
    solution: ['Qc6'],
    hints: ['퀸을 활용하여 킹을 공격하세요. (참고: 이 퍼즐은 메이트가 아닌 강제 승으로 이어지는 수입니다.)'],
  },
  {
    id: 'mi1-005',
    title: '1수 체크메이트 #5',
    description: '백이 한 수로 체크메이트할 수 있습니다.',
    difficulty: 1,
    fen: 'r1bqk2r/pppp1Bpp/2n2n2/2b1p3/4P3/8/PPPP1PPP/RNBQK1NR b KQkq - 0 4',
    turn: 'w',
    solution: ['Bxf7+'],
    hints: ['비숍으로 f7을 공격하세요.'],
  },
  {
    id: 'mi1-006',
    title: '1수 체크메이트 #6',
    description: '백이 한 수로 체크메이트할 수 있습니다.',
    difficulty: 1,
    fen: 'r1b1k2r/ppppqppp/2n2n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 5',
    turn: 'w',
    solution: ['Bg5'],
    hints: ['흑 퀸이나 나이트를 핀으로 묶으세요.'],
  },
  {
    id: 'mi1-007',
    title: '백 룩 메이트',
    description: '백 룩으로 체크메이트하세요.',
    difficulty: 1,
    fen: '4k3/8/4K3/8/8/8/8/R7 w - - 0 1',
    turn: 'w',
    solution: ['Ra8#'],
    hints: ['룩으로 8랭크 공격!'],
  },
  {
    id: 'mi1-008',
    title: '퀸 체크메이트',
    description: '백이 퀸으로 체크메이트할 수 있습니다.',
    difficulty: 1,
    fen: 'k7/8/1K6/8/8/8/8/Q7 w - - 0 1',
    turn: 'w',
    solution: ['Qa7#'],
    hints: ['퀸을 a7으로 보내세요.'],
  },
  {
    id: 'mi1-009',
    title: '비숍+룩 메이트',
    description: '한 수로 체크메이트하세요.',
    difficulty: 1,
    fen: '6k1/5ppp/8/8/1B6/8/5PPP/4R1K1 w - - 0 1',
    turn: 'w',
    solution: ['Re8#'],
    hints: ['룩을 8랭크로!'],
  },
  {
    id: 'mi1-010',
    title: '나이트 체크메이트',
    description: '나이트로 체크메이트하세요.',
    difficulty: 2,
    fen: 'r1bqkb1r/pppppppp/2N2n2/8/8/8/PPPPPPPP/R1BQKBNR w KQkq - 0 1',
    turn: 'w',
    solution: ['Nxd8'],
    hints: ['나이트로 퀸을 잡으세요. (이 퍼즐은 기물 잡기 문제입니다.)'],
  },
];
