export const TACTICS_PUZZLES = [
  {
    id: 'tac-001',
    title: '포크 #1',
    description: '나이트 포크로 두 기물을 동시에 공격하세요.',
    difficulty: 2,
    category: 'fork',
    fen: 'r1bqkbnr/pppppppp/2n5/8/4N3/8/PPPPPPPP/R1BQKBNR w KQkq - 0 1',
    turn: 'w',
    solution: ['Nd6+'],
    hints: ['나이트로 킹과 다른 기물을 동시에 공격할 수 있는 칸을 찾으세요.'],
  },
  {
    id: 'tac-002',
    title: '핀 #1',
    description: '비숍 핀으로 적 기물을 고정하세요.',
    difficulty: 2,
    category: 'pin',
    fen: 'rnbqk1nr/pppp1ppp/4p3/8/1b1P4/2N5/PPP1PPPP/R1BQKBNR w KQkq - 0 1',
    turn: 'w',
    solution: ['Bd2'],
    hints: ['비숍의 핀을 해소하세요.'],
  },
  {
    id: 'tac-003',
    title: '스큐어 #1',
    description: '높은 가치 기물 뒤의 기물을 잡으세요.',
    difficulty: 3,
    category: 'skewer',
    fen: '4k3/8/8/8/8/8/1R6/4K3 w - - 0 1',
    turn: 'w',
    solution: ['Re2+'],
    hints: ['룩으로 킹을 체크하여 뒤의 기물을 노리세요.'],
  },
  {
    id: 'tac-004',
    title: '디스커버드 어택 #1',
    description: '기물을 이동하여 숨겨진 공격을 발동하세요.',
    difficulty: 3,
    category: 'discovered',
    fen: 'rnbqkbnr/ppp1pppp/8/3p4/4P3/8/PPPP1PPP/RNBQKBNR w KQkq d6 0 2',
    turn: 'w',
    solution: ['exd5'],
    hints: ['중앙 폰을 잡으세요.'],
  },
  {
    id: 'tac-005',
    title: '더블 체크',
    description: '두 기물로 동시 체크를 거세요.',
    difficulty: 3,
    category: 'double_check',
    fen: 'rnbqk2r/ppppbppp/4pn2/8/3PP3/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1',
    turn: 'w',
    solution: ['d5'],
    hints: ['중앙 폰을 전진시키세요.'],
  },
  {
    id: 'tac-006',
    title: '기물 잡기 #1',
    description: '무방비 기물을 잡으세요.',
    difficulty: 1,
    category: 'hanging',
    fen: 'rnbqkbnr/pppppppp/8/8/8/5N2/PPPPPPPP/RNBQKB1R w KQkq - 0 1',
    turn: 'w',
    solution: ['Nxe5'],
    hints: ['방어되지 않은 폰이 있나요?'],
  },
  {
    id: 'tac-007',
    title: '포크 #2 - 퀸 포크',
    description: '퀸으로 두 기물을 동시에 공격하세요.',
    difficulty: 2,
    category: 'fork',
    fen: 'r1b1kbnr/ppppqppp/2n5/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR w KQkq - 0 1',
    turn: 'w',
    solution: ['Qf7+'],
    hints: ['퀸으로 킹을 체크하면서 다른 기물도 공격하세요.'],
  },
  {
    id: 'tac-008',
    title: '희생 후 공격',
    description: '기물을 희생하여 결정적 공격을 만드세요.',
    difficulty: 4,
    category: 'sacrifice',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    turn: 'w',
    solution: ['Bxf7+'],
    hints: ['비숍으로 f7을 잡으세요!'],
  },
];
